[2025-06-11T16:02:10.871+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_us.process_marketing_campaigns_us manual__2025-06-11T15:56:28.438220+00:00 [queued]>
[2025-06-11T16:02:10.897+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_us.process_marketing_campaigns_us manual__2025-06-11T15:56:28.438220+00:00 [queued]>
[2025-06-11T16:02:10.898+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-11T16:02:10.949+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_us.process_marketing_campaigns_us> on 2025-06-11 15:56:28.438220+00:00
[2025-06-11T16:02:10.987+0000] {standard_task_runner.py:60} INFO - Started process 11149 to run task
[2025-06-11T16:02:11.003+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_transform_staging_v2', 'process_region_us.process_marketing_campaigns_us', 'manual__2025-06-11T15:56:28.438220+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmp5d25ckgf']
[2025-06-11T16:02:11.009+0000] {standard_task_runner.py:88} INFO - Job 152: Subtask process_region_us.process_marketing_campaigns_us
[2025-06-11T16:02:11.229+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_transform_staging_v2.process_region_us.process_marketing_campaigns_us manual__2025-06-11T15:56:28.438220+00:00 [running]> on host 5950010ae7c1
[2025-06-11T16:02:11.744+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_transform_staging_v2' AIRFLOW_CTX_TASK_ID='process_region_us.process_marketing_campaigns_us' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T15:56:28.438220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T15:56:28.438220+00:00'
[2025-06-11T16:02:48.418+0000] {logging_mixin.py:188} INFO - Debugggg::::Vector(spark://5950010ae7c1:44919/jars/snowflake-jdbc-3.13.17.jar, spark://5950010ae7c1:44919/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar)
[2025-06-11T16:02:48.582+0000] {logging_mixin.py:188} INFO - Processing marketing_campaigns for region us
[2025-06-11T16:02:49.613+0000] {logging_mixin.py:188} INFO - /opt/airflow/data/raw/region=us/table=marketing_campaigns/load_date=2025-06-11
[2025-06-11T16:03:40.304+0000] {logging_mixin.py:188} INFO - Error processing marketing_campaigns for us: transform_marketing_campaigns_us() takes 1 positional argument but 2 were given
[2025-06-11T16:03:42.033+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_dag.py", line 242, in process_table
    df_transformed = transform_func(df_raw, region,exchange_rates)
  File "/opt/airflow/scripts/etl/transform/marketing_campaigns.py", line 97, in transform_marketing_campaigns
    return transform_marketing_campaigns_us(df, exchange_rates)
TypeError: transform_marketing_campaigns_us() takes 1 positional argument but 2 were given
[2025-06-11T16:03:42.156+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_region_transform_staging_v2, task_id=process_region_us.process_marketing_campaigns_us, execution_date=20250611T155628, start_date=20250611T160210, end_date=20250611T160342
[2025-06-11T16:03:43.709+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 152 for task process_region_us.process_marketing_campaigns_us (transform_marketing_campaigns_us() takes 1 positional argument but 2 were given; 11149)
[2025-06-11T16:03:43.793+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T16:03:44.465+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
