[2025-06-11T12:32:25.915+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_asia.process_discounts_asia manual__2025-06-11T12:30:24.798327+00:00 [queued]>
[2025-06-11T12:32:25.946+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_transform_staging_v2.process_region_asia.process_discounts_asia manual__2025-06-11T12:30:24.798327+00:00 [queued]>
[2025-06-11T12:32:25.946+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-11T12:32:25.980+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_asia.process_discounts_asia> on 2025-06-11 12:30:24.798327+00:00
[2025-06-11T12:32:25.999+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-11T12:32:25.996+0000] {standard_task_runner.py:60} INFO - Started process 53744 to run task
[2025-06-11T12:32:26.009+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_transform_staging_v2', 'process_region_asia.process_discounts_asia', 'manual__2025-06-11T12:30:24.798327+00:00', '--job-id', '1752', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmpgekm8509']
[2025-06-11T12:32:26.012+0000] {standard_task_runner.py:88} INFO - Job 1752: Subtask process_region_asia.process_discounts_asia
[2025-06-11T12:32:26.176+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_transform_staging_v2.process_region_asia.process_discounts_asia manual__2025-06-11T12:30:24.798327+00:00 [running]> on host 8b0a421f0af7
[2025-06-11T12:32:26.453+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_transform_staging_v2' AIRFLOW_CTX_TASK_ID='process_region_asia.process_discounts_asia' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T12:30:24.798327+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T12:30:24.798327+00:00'
[2025-06-11T12:32:26.461+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_dag.py", line 188, in process_table
    spark = get_spark_session()
TypeError: get_spark_session() missing 1 required positional argument: 'app_name'
[2025-06-11T12:32:26.496+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=multi_region_transform_staging_v2, task_id=process_region_asia.process_discounts_asia, execution_date=20250611T123024, start_date=20250611T123225, end_date=20250611T123226
[2025-06-11T12:32:26.610+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-06-11T12:32:26.611+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-11T12:32:26.611+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-06-11T12:32:26.614+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-11T12:32:26.626+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1752 for task process_region_asia.process_discounts_asia (get_spark_session() missing 1 required positional argument: 'app_name'; 53744)
[2025-06-11T12:32:26.663+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T12:32:26.750+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
