[2025-06-03T07:52:41.471+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_raw_data_asia.extract_asia_asia_ab_test_variants scheduled__2025-06-02T00:00:00+00:00 [queued]>
[2025-06-03T07:52:41.491+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_raw_data_asia.extract_asia_asia_ab_test_variants scheduled__2025-06-02T00:00:00+00:00 [queued]>
[2025-06-03T07:52:41.492+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-03T07:52:41.645+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extract_asia_asia_ab_test_variants> on 2025-06-02 00:00:00+00:00
[2025-06-03T07:52:41.674+0000] {standard_task_runner.py:60} INFO - Started process 257 to run task
[2025-06-03T07:52:41.684+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_raw_data_asia', 'extract_asia_asia_ab_test_variants', 'scheduled__2025-06-02T00:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/asia/landing.py', '--cfg-path', '/tmp/tmpk15x9l3b']
[2025-06-03T07:52:41.692+0000] {standard_task_runner.py:88} INFO - Job 270: Subtask extract_asia_asia_ab_test_variants
[2025-06-03T07:52:41.826+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-03T07:52:41.970+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_raw_data_asia.extract_asia_asia_ab_test_variants scheduled__2025-06-02T00:00:00+00:00 [running]> on host 86069ee61878
[2025-06-03T07:52:42.670+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_raw_data_asia' AIRFLOW_CTX_TASK_ID='extract_asia_asia_ab_test_variants' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-02T00:00:00+00:00'
[2025-06-03T07:52:42.671+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-03T07:52:42.671+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                spark-submit                     /opt/airflow/scripts/pyspark_jobs/extract_to_parquet.py                     asia.ab_test_variants "jdbc:postgresql://retail-postgres:5432/retail_etl" retail-etl retail_etl 2025-06-02\n            ']
[2025-06-03T07:52:42.678+0000] {subprocess.py:86} INFO - Output:
[2025-06-03T07:55:08.059+0000] {subprocess.py:93} INFO - 25/06/03 07:55:07 INFO SparkContext: Running Spark version 3.5.6
[2025-06-03T07:55:08.293+0000] {subprocess.py:93} INFO - 25/06/03 07:55:08 INFO SparkContext: OS info Linux, 6.11.0-26-generic, amd64
[2025-06-03T07:55:08.293+0000] {subprocess.py:93} INFO - 25/06/03 07:55:08 INFO SparkContext: Java version 11.0.24
[2025-06-03T07:55:10.975+0000] {subprocess.py:93} INFO - 25/06/03 07:55:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-03T07:55:14.114+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceUtils: ==============================================================
[2025-06-03T07:55:14.114+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-03T07:55:14.115+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceUtils: ==============================================================
[2025-06-03T07:55:14.115+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO SparkContext: Submitted application: Extract_asia_asia.ab_test_variants
[2025-06-03T07:55:15.131+0000] {subprocess.py:93} INFO - 25/06/03 07:55:15 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-03T07:55:15.140+0000] {subprocess.py:93} INFO - 25/06/03 07:55:15 INFO ResourceProfile: Limiting resource is cpu
[2025-06-03T07:55:15.141+0000] {subprocess.py:93} INFO - 25/06/03 07:55:15 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-03T07:55:21.257+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing view acls to: airflow
[2025-06-03T07:55:21.258+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing modify acls to: airflow
[2025-06-03T07:55:21.259+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing view acls groups to:
[2025-06-03T07:55:21.260+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing modify acls groups to:
[2025-06-03T07:55:21.261+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-06-03T07:55:39.470+0000] {subprocess.py:93} INFO - 25/06/03 07:55:39 INFO Utils: Successfully started service 'sparkDriver' on port 34273.
[2025-06-03T07:55:40.789+0000] {subprocess.py:93} INFO - 25/06/03 07:55:40 INFO SparkEnv: Registering MapOutputTracker
[2025-06-03T07:55:42.204+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-03T07:55:42.617+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-03T07:55:42.618+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-03T07:55:42.831+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-03T07:55:43.663+0000] {subprocess.py:93} INFO - 25/06/03 07:55:43 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0e37a6af-bfa9-4b51-b4e5-f0837486b807
[2025-06-03T07:55:44.048+0000] {subprocess.py:93} INFO - 25/06/03 07:55:44 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-03T07:55:44.437+0000] {subprocess.py:93} INFO - 25/06/03 07:55:44 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-03T07:55:48.382+0000] {subprocess.py:93} INFO - 25/06/03 07:55:48 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-06-03T07:55:51.346+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-06-03T07:55:51.352+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-06-03T07:55:51.353+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-06-03T07:55:51.366+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-06-03T07:55:51.366+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2025-06-03T07:55:51.368+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2025-06-03T07:55:51.371+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2025-06-03T07:55:51.374+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2025-06-03T07:55:51.378+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2025-06-03T07:55:51.379+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2025-06-03T07:55:51.384+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2025-06-03T07:55:51.387+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
[2025-06-03T07:55:51.390+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
[2025-06-03T07:55:51.390+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4053. Attempting port 4054.
[2025-06-03T07:55:51.461+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 INFO Utils: Successfully started service 'SparkUI' on port 4054.
[2025-06-03T07:55:52.593+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Starting executor ID driver on host 86069ee61878
[2025-06-03T07:55:52.597+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: OS info Linux, 6.11.0-26-generic, amd64
[2025-06-03T07:55:52.597+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Java version 11.0.24
[2025-06-03T07:55:52.625+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-06-03T07:55:52.626+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@43e3ec2d for default.
[2025-06-03T07:55:53.617+0000] {subprocess.py:93} INFO - 25/06/03 07:55:53 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34737.
[2025-06-03T07:55:53.618+0000] {subprocess.py:93} INFO - 25/06/03 07:55:53 INFO NettyBlockTransferService: Server created on 86069ee61878:34737
[2025-06-03T07:55:53.681+0000] {subprocess.py:93} INFO - 25/06/03 07:55:53 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-03T07:55:54.518+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 86069ee61878, 34737, None)
[2025-06-03T07:55:54.522+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManagerMasterEndpoint: Registering block manager 86069ee61878:34737 with 434.4 MiB RAM, BlockManagerId(driver, 86069ee61878, 34737, None)
[2025-06-03T07:55:54.556+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 86069ee61878, 34737, None)
[2025-06-03T07:55:54.560+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 86069ee61878, 34737, None)
[2025-06-03T07:56:06.988+0000] {subprocess.py:93} INFO - 25/06/03 07:56:06 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-03T07:56:07.239+0000] {subprocess.py:93} INFO - 25/06/03 07:56:07 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpjxgbd2hi/spark-warehouse'.
[2025-06-03T07:56:33.674+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-03T07:56:33.674+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/pyspark_jobs/extract_to_parquet.py", line 24, in <module>
[2025-06-03T07:56:33.674+0000] {subprocess.py:93} INFO -     .load()
[2025-06-03T07:56:33.675+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2025-06-03T07:56:33.675+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-06-03T07:56:33.675+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-06-03T07:56:33.675+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-06-03T07:56:33.696+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o30.load.
[2025-06-03T07:56:33.696+0000] {subprocess.py:93} INFO - : java.lang.ClassNotFoundException: org.postgresql.Driver
[2025-06-03T07:56:33.697+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2025-06-03T07:56:33.697+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2025-06-03T07:56:33.697+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2025-06-03T07:56:33.697+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
[2025-06-03T07:56:33.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
[2025-06-03T07:56:33.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
[2025-06-03T07:56:33.698+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-06-03T07:56:33.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
[2025-06-03T07:56:33.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
[2025-06-03T07:56:33.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
[2025-06-03T07:56:33.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
[2025-06-03T07:56:33.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-06-03T07:56:33.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-06-03T07:56:33.699+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-06-03T07:56:33.717+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-06-03T07:56:33.717+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-06-03T07:56:33.727+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-06-03T07:56:33.728+0000] {subprocess.py:93} INFO - 
[2025-06-03T07:56:34.041+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-03T07:56:34.041+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-06-03T07:56:34.140+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO SparkUI: Stopped Spark web UI at http://86069ee61878:4054
[2025-06-03T07:56:34.281+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-03T07:56:35.664+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO MemoryStore: MemoryStore cleared
[2025-06-03T07:56:35.666+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO BlockManager: BlockManager stopped
[2025-06-03T07:56:35.772+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-03T07:56:35.829+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-03T07:56:35.917+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO SparkContext: Successfully stopped SparkContext
[2025-06-03T07:56:35.919+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Shutdown hook called
[2025-06-03T07:56:35.920+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-41ede52d-cf0c-4e32-aa58-84f610ee4db3
[2025-06-03T07:56:35.934+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-aa53774c-e18a-4608-b494-e98fd91f8a81
[2025-06-03T07:56:35.946+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-41ede52d-cf0c-4e32-aa58-84f610ee4db3/pyspark-40039815-5f9e-4b7a-a3b9-0f6730e96385
[2025-06-03T07:56:36.418+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-03T07:56:42.625+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-03T07:56:44.986+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_raw_data_asia, task_id=extract_asia_asia_ab_test_variants, execution_date=20250602T000000, start_date=20250603T075241, end_date=20250603T075643
[2025-06-03T07:56:56.836+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 270 for task extract_asia_asia_ab_test_variants (Bash command failed. The command returned a non-zero exit code 1.; 257)
[2025-06-03T07:56:59.667+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-03T07:59:01.795+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
