[2025-06-09T04:54:01.019+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_processor_alternative.process_categories_eu scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-09T04:54:01.044+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_processor_alternative.process_categories_eu scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-09T04:54:01.045+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-09T04:54:01.131+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_categories_eu> on 2025-06-08 00:00:00+00:00
[2025-06-09T04:54:01.147+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-09T04:54:01.145+0000] {standard_task_runner.py:60} INFO - Started process 1107 to run task
[2025-06-09T04:54:01.155+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_processor_alternative', 'process_categories_eu', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/dag_run.py', '--cfg-path', '/tmp/tmpb5x0kv2r']
[2025-06-09T04:54:01.158+0000] {standard_task_runner.py:88} INFO - Job 151: Subtask process_categories_eu
[2025-06-09T04:54:01.262+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-09T04:54:01.388+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_processor_alternative.process_categories_eu scheduled__2025-06-08T00:00:00+00:00 [running]> on host 847c6af56c4f
[2025-06-09T04:54:01.949+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_processor_alternative' AIRFLOW_CTX_TASK_ID='process_categories_eu' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-09T04:54:01.964+0000] {logging_mixin.py:188} INFO - üîÑ Processing categories for region eu
[2025-06-09T04:54:01.965+0000] {logging_mixin.py:188} INFO - üìÇ Input path: /opt/airflow/data/raw/region=eu/table=categories/load_date=2025-06-08/
[2025-06-09T04:54:01.965+0000] {logging_mixin.py:188} INFO - üìÅ Output path: /opt/airflow/data/processed/region=eu/table=categories/load_date=2025-06-08/
[2025-06-09T04:54:01.965+0000] {logging_mixin.py:188} INFO - üìñ Reading data from /opt/airflow/data/raw/region=eu/table=categories/load_date=2025-06-08/
[2025-06-09T04:54:11.464+0000] {logging_mixin.py:188} INFO - üîß Applying transformation for categories
[2025-06-09T04:54:12.748+0000] {logging_mixin.py:188} INFO - üíæ Writing transformed data to /opt/airflow/data/processed/region=eu/table=categories/load_date=2025-06-08/
[2025-06-09T04:54:26.155+0000] {logging_mixin.py:188} INFO - +-----------+-------------+-------------------+------------------+--------------------+---------+--------------+-------------------+-------------------+-------+--------+
|category_id|category_name|category_name_local|parent_category_id|       category_path|is_active|gdpr_sensitive|         created_at|         updated_at|_region| _source|
+-----------+-------------+-------------------+------------------+--------------------+---------+--------------+-------------------+-------------------+-------+--------+
|          1|  Electronics|         Elektronik|              NULL|        /Electronics|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          2|  Smartphones|        Smartphones|                 1|/Electronics/Smar...|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          3|      Laptops|            Laptops|                 1|/Electronics/Laptops|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          4|       Gaming|             Spiele|                 1| /Electronics/Gaming|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          5|     Clothing|           Kleidung|              NULL|           /Clothing|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          6|    Mens Wear|   Herrenbekleidung|                 5|      /Clothing/Mens|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          7|  Womens Wear|    Damenbekleidung|                 5|    /Clothing/Womens|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          8|Home & Garden|      Haus & Garten|              NULL|        /Home-Garden|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|          9|    Furniture|              M√∂bel|                 8|/Home-Garden/Furn...|        1|         false|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
|         10|        Books|             B√ºcher|              NULL|              /Books|        1|          true|2025-06-08 19:22:57|2025-06-08 19:22:57|     eu|postgres|
+-----------+-------------+-------------------+------------------+--------------------+---------+--------------+-------------------+-------------------+-------+--------+
only showing top 10 rows
[2025-06-09T04:54:27.932+0000] {logging_mixin.py:188} INFO - ‚úÖ Successfully processed 30 records for categories in eu
[2025-06-09T04:54:27.933+0000] {logging_mixin.py:188} INFO - üõë Stopping Spark session for categories_eu
[2025-06-09T06:55:46.758+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_processor_alternative.process_categories_eu scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-09T06:55:46.777+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_processor_alternative.process_categories_eu scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-09T06:55:46.777+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-09T06:55:46.804+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_categories_eu> on 2025-06-08 00:00:00+00:00
[2025-06-09T06:55:46.814+0000] {standard_task_runner.py:60} INFO - Started process 41374 to run task
[2025-06-09T06:55:46.819+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_processor_alternative', 'process_categories_eu', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag_run.py', '--cfg-path', '/tmp/tmpw6yc3flz']
[2025-06-09T06:55:46.821+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask process_categories_eu
[2025-06-09T06:55:46.849+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-09T06:55:46.938+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_processor_alternative.process_categories_eu scheduled__2025-06-08T00:00:00+00:00 [running]> on host afcdbcf38bc0
[2025-06-09T06:55:47.139+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_processor_alternative' AIRFLOW_CTX_TASK_ID='process_categories_eu' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-09T06:55:52.821+0000] {logging_mixin.py:188} INFO - Error processing categories for eu: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-06-09T06:55:52.822+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/dag_run.py", line 129, in process_table
    spark = get_spark_session(f"Process_{table}_{region}_{load_date}")
  File "/opt/airflow/dags/dag_run.py", line 115, in get_spark_session
    .getOrCreate()
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_run.py", line 176, in process_table
    raise Exception(error_msg)
Exception: Error processing categories for eu: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-06-09T06:55:52.850+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_region_processor_alternative, task_id=process_categories_eu, execution_date=20250608T000000, start_date=20250609T065546, end_date=20250609T065552
[2025-06-09T06:55:52.886+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 28 for task process_categories_eu (Error processing categories for eu: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 41374)
[2025-06-09T06:55:52.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-09T06:55:53.098+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
