[2025-06-03T07:52:41.496+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_raw_data_asia.extract_asia_asia_inventory scheduled__2025-06-02T00:00:00+00:00 [queued]>
[2025-06-03T07:52:41.509+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_raw_data_asia.extract_asia_asia_inventory scheduled__2025-06-02T00:00:00+00:00 [queued]>
[2025-06-03T07:52:41.509+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 2
[2025-06-03T07:52:41.638+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extract_asia_asia_inventory> on 2025-06-02 00:00:00+00:00
[2025-06-03T07:52:41.646+0000] {standard_task_runner.py:60} INFO - Started process 244 to run task
[2025-06-03T07:52:41.657+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_raw_data_asia', 'extract_asia_asia_inventory', 'scheduled__2025-06-02T00:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/asia/landing.py', '--cfg-path', '/tmp/tmpt2_79su7']
[2025-06-03T07:52:41.661+0000] {standard_task_runner.py:88} INFO - Job 274: Subtask extract_asia_asia_inventory
[2025-06-03T07:52:41.769+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-03T07:52:41.874+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_raw_data_asia.extract_asia_asia_inventory scheduled__2025-06-02T00:00:00+00:00 [running]> on host 86069ee61878
[2025-06-03T07:52:42.916+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_raw_data_asia' AIRFLOW_CTX_TASK_ID='extract_asia_asia_inventory' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-02T00:00:00+00:00'
[2025-06-03T07:52:42.917+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-03T07:52:42.917+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                spark-submit                     /opt/airflow/scripts/pyspark_jobs/extract_to_parquet.py                     asia.inventory "jdbc:postgresql://retail-postgres:5432/retail_etl" retail-etl retail_etl 2025-06-02\n            ']
[2025-06-03T07:52:42.925+0000] {subprocess.py:86} INFO - Output:
[2025-06-03T07:55:08.059+0000] {subprocess.py:93} INFO - 25/06/03 07:55:07 INFO SparkContext: Running Spark version 3.5.6
[2025-06-03T07:55:08.286+0000] {subprocess.py:93} INFO - 25/06/03 07:55:08 INFO SparkContext: OS info Linux, 6.11.0-26-generic, amd64
[2025-06-03T07:55:08.287+0000] {subprocess.py:93} INFO - 25/06/03 07:55:08 INFO SparkContext: Java version 11.0.24
[2025-06-03T07:55:10.975+0000] {subprocess.py:93} INFO - 25/06/03 07:55:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-03T07:55:14.532+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceUtils: ==============================================================
[2025-06-03T07:55:14.533+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-03T07:55:14.542+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceUtils: ==============================================================
[2025-06-03T07:55:14.543+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO SparkContext: Submitted application: Extract_asia_asia.inventory
[2025-06-03T07:55:14.829+0000] {subprocess.py:93} INFO - 25/06/03 07:55:14 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-03T07:55:17.463+0000] {subprocess.py:93} INFO - 25/06/03 07:55:17 INFO ResourceProfile: Limiting resource is cpu
[2025-06-03T07:55:17.464+0000] {subprocess.py:93} INFO - 25/06/03 07:55:17 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-03T07:55:21.236+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing view acls to: airflow
[2025-06-03T07:55:21.237+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing modify acls to: airflow
[2025-06-03T07:55:21.241+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing view acls groups to:
[2025-06-03T07:55:21.242+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: Changing modify acls groups to:
[2025-06-03T07:55:21.243+0000] {subprocess.py:93} INFO - 25/06/03 07:55:21 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-06-03T07:55:39.007+0000] {subprocess.py:93} INFO - 25/06/03 07:55:39 INFO Utils: Successfully started service 'sparkDriver' on port 36181.
[2025-06-03T07:55:40.790+0000] {subprocess.py:93} INFO - 25/06/03 07:55:40 INFO SparkEnv: Registering MapOutputTracker
[2025-06-03T07:55:42.203+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-03T07:55:42.619+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-03T07:55:42.620+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-03T07:55:42.832+0000] {subprocess.py:93} INFO - 25/06/03 07:55:42 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-03T07:55:43.666+0000] {subprocess.py:93} INFO - 25/06/03 07:55:43 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b20ff7f6-9c65-4b12-a408-00d15418b58b
[2025-06-03T07:55:44.048+0000] {subprocess.py:93} INFO - 25/06/03 07:55:44 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-03T07:55:44.442+0000] {subprocess.py:93} INFO - 25/06/03 07:55:44 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-03T07:55:48.373+0000] {subprocess.py:93} INFO - 25/06/03 07:55:48 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-06-03T07:55:51.349+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-06-03T07:55:51.350+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-06-03T07:55:51.356+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-06-03T07:55:51.363+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-06-03T07:55:51.363+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2025-06-03T07:55:51.364+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2025-06-03T07:55:51.364+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2025-06-03T07:55:51.364+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2025-06-03T07:55:51.374+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2025-06-03T07:55:51.374+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2025-06-03T07:55:51.417+0000] {subprocess.py:93} INFO - 25/06/03 07:55:51 INFO Utils: Successfully started service 'SparkUI' on port 4050.
[2025-06-03T07:55:52.627+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Starting executor ID driver on host 86069ee61878
[2025-06-03T07:55:52.629+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: OS info Linux, 6.11.0-26-generic, amd64
[2025-06-03T07:55:52.632+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Java version 11.0.24
[2025-06-03T07:55:52.641+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-06-03T07:55:52.642+0000] {subprocess.py:93} INFO - 25/06/03 07:55:52 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@4e27a575 for default.
[2025-06-03T07:55:53.609+0000] {subprocess.py:93} INFO - 25/06/03 07:55:53 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43667.
[2025-06-03T07:55:53.610+0000] {subprocess.py:93} INFO - 25/06/03 07:55:53 INFO NettyBlockTransferService: Server created on 86069ee61878:43667
[2025-06-03T07:55:53.681+0000] {subprocess.py:93} INFO - 25/06/03 07:55:53 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-03T07:55:54.503+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 86069ee61878, 43667, None)
[2025-06-03T07:55:54.519+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManagerMasterEndpoint: Registering block manager 86069ee61878:43667 with 434.4 MiB RAM, BlockManagerId(driver, 86069ee61878, 43667, None)
[2025-06-03T07:55:54.535+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 86069ee61878, 43667, None)
[2025-06-03T07:55:54.537+0000] {subprocess.py:93} INFO - 25/06/03 07:55:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 86069ee61878, 43667, None)
[2025-06-03T07:56:06.931+0000] {subprocess.py:93} INFO - 25/06/03 07:56:06 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-03T07:56:07.238+0000] {subprocess.py:93} INFO - 25/06/03 07:56:07 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpxjm1dd0j/spark-warehouse'.
[2025-06-03T07:56:33.675+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-03T07:56:33.675+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/pyspark_jobs/extract_to_parquet.py", line 24, in <module>
[2025-06-03T07:56:33.677+0000] {subprocess.py:93} INFO -     .load()
[2025-06-03T07:56:33.717+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2025-06-03T07:56:33.717+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-06-03T07:56:33.717+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO -   File "/usr/local/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o30.load.
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - : java.lang.ClassNotFoundException: org.postgresql.Driver
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2025-06-03T07:56:33.718+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-06-03T07:56:33.719+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
[2025-06-03T07:56:33.720+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
[2025-06-03T07:56:33.726+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
[2025-06-03T07:56:33.727+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
[2025-06-03T07:56:33.727+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-06-03T07:56:33.727+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-06-03T07:56:33.727+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-06-03T07:56:33.727+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-06-03T07:56:33.728+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2025-06-03T07:56:33.728+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-06-03T07:56:33.728+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-06-03T07:56:33.728+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-06-03T07:56:33.728+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-06-03T07:56:33.729+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-06-03T07:56:33.730+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-06-03T07:56:33.737+0000] {subprocess.py:93} INFO - 
[2025-06-03T07:56:34.039+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-03T07:56:34.040+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-06-03T07:56:34.135+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO SparkUI: Stopped Spark web UI at http://86069ee61878:4050
[2025-06-03T07:56:34.286+0000] {subprocess.py:93} INFO - 25/06/03 07:56:34 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-03T07:56:35.689+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO MemoryStore: MemoryStore cleared
[2025-06-03T07:56:35.695+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO BlockManager: BlockManager stopped
[2025-06-03T07:56:35.737+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-03T07:56:35.747+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-03T07:56:35.820+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO SparkContext: Successfully stopped SparkContext
[2025-06-03T07:56:35.821+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Shutdown hook called
[2025-06-03T07:56:35.829+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-11d6f017-dab1-4603-b594-ce389390a74a
[2025-06-03T07:56:35.838+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-af428eaa-b2bf-4d7c-ad72-72a8974f57d5
[2025-06-03T07:56:35.851+0000] {subprocess.py:93} INFO - 25/06/03 07:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-11d6f017-dab1-4603-b594-ce389390a74a/pyspark-534ea09f-2916-4e52-af05-4d2b4f6f126e
[2025-06-03T07:56:36.418+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-03T07:56:39.970+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-03T07:56:45.017+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_raw_data_asia, task_id=extract_asia_asia_inventory, execution_date=20250602T000000, start_date=20250603T075241, end_date=20250603T075641
[2025-06-03T07:57:06.011+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 274 for task extract_asia_asia_inventory (Bash command failed. The command returned a non-zero exit code 1.; 244)
[2025-06-03T07:57:15.245+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-03T07:59:43.201+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
