[2025-06-11T15:54:02.448+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: geography_to_snowflake.Load_geography_method manual__2025-06-11T14:38:35.644637+00:00 [queued]>
[2025-06-11T15:54:02.516+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: geography_to_snowflake.Load_geography_method manual__2025-06-11T14:38:35.644637+00:00 [queued]>
[2025-06-11T15:54:02.517+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 2
[2025-06-11T15:54:02.561+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Load_geography_method> on 2025-06-11 14:38:35.644637+00:00
[2025-06-11T15:54:02.580+0000] {standard_task_runner.py:60} INFO - Started process 296 to run task
[2025-06-11T15:54:02.590+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'geography_to_snowflake', 'Load_geography_method', 'manual__2025-06-11T14:38:35.644637+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/star/geography.py', '--cfg-path', '/tmp/tmprd0g4ldk']
[2025-06-11T15:54:02.595+0000] {standard_task_runner.py:88} INFO - Job 135: Subtask Load_geography_method
[2025-06-11T15:54:02.812+0000] {task_command.py:423} INFO - Running <TaskInstance: geography_to_snowflake.Load_geography_method manual__2025-06-11T14:38:35.644637+00:00 [running]> on host 5950010ae7c1
[2025-06-11T15:54:03.621+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='geography_to_snowflake' AIRFLOW_CTX_TASK_ID='Load_geography_method' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T14:38:35.644637+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T14:38:35.644637+00:00'
[2025-06-11T15:55:34.604+0000] {logging_mixin.py:188} INFO - Data written to temporary Snowflake table.
[2025-06-11T15:55:35.491+0000] {connection.py:486} INFO - Snowflake Connector for Python Version: 3.15.0, Python Version: 3.10.13, Platform: Linux-6.11.0-26-generic-x86_64-with-glibc2.36
[2025-06-11T15:55:36.004+0000] {connection.py:1391} INFO - Connecting to GLOBAL Snowflake domain
[2025-06-11T15:55:49.961+0000] {logging_mixin.py:188} INFO - Merge operation completed successfully.
[2025-06-11T15:55:50.594+0000] {connection.py:486} INFO - Snowflake Connector for Python Version: 3.15.0, Python Version: 3.10.13, Platform: Linux-6.11.0-26-generic-x86_64-with-glibc2.36
[2025-06-11T15:55:50.595+0000] {connection.py:1391} INFO - Connecting to GLOBAL Snowflake domain
[2025-06-11T15:55:52.925+0000] {logging_mixin.py:188} INFO - Temporary table STAR.DIM_GEOGRAPHY_TEMP dropped successfully.
[2025-06-11T15:55:53.572+0000] {logging_mixin.py:188} INFO - Upsert completed from Spark CSV to Snowflake.
[2025-06-11T15:55:53.573+0000] {logging_mixin.py:188} INFO - Successfully completed processing.
[2025-06-11T15:55:53.577+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-11T15:55:53.773+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=geography_to_snowflake, task_id=Load_geography_method, execution_date=20250611T143835, start_date=20250611T155402, end_date=20250611T155553
[2025-06-11T15:55:53.925+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-11T15:55:54.154+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
